# Generated by Django 4.1.1 on 2023-02-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Contact",),
    ]
